FROM dockron
#COPY --from=dockron /usr/local/bin/dockron /usr/local/bin/dockron
#curl -o https://github.com/stzups/dockron/releases/download/1.0.0/dockron /usr/local/bin/dockron https://github.com
CMD [ "dockron", "echo", "hello" ]
